from __future__ import annotations

from typing import Any, Dict, List


FALLBACK_EVIDENCE_POOL: List[Dict[str, Any]] = [
    {
        "id": "visual_meituan_merchant_manual",
        "title": "Meituan Waimai new merchant service manual",
        "url": "https://s3plus.meituan.net/v1/mss_1161d28e78554b4390e03672b19f818f/waimai-cd-fe-agent/%E6%96%B0%E5%95%86%E5%AE%B6%E6%9C%8D%E5%8A%A1%E6%89%8B%E5%86%8C.pdf",
        "workflow": "小餐馆视觉营销物料制作与发布工作流",
        "proof_point": "外卖平台经营需要商家维护店铺图、商品图、促销信息和线上展示素材。",
        "step_refs": ["店铺信息维护", "菜品图片维护", "促销信息配置", "平台发布"],
        "inefficiencies": ["信息搬运", "人工重复"],
        "source_type": "platform_manual",
    },
    {
        "id": "visual_designkit_food_poster",
        "title": "美图设计室：美食探店海报制作",
        "url": "https://www.designkit.cn/article/meishitandian-haibao",
        "workflow": "小餐馆视觉营销物料制作与发布工作流",
        "proof_point": "菜品原图、主体识别、排版和文案组合是餐饮海报制作的实际设计步骤。",
        "step_refs": ["上传菜品原图", "主体识别", "模板排版", "海报导出"],
        "inefficiencies": ["判断成本", "人工重复"],
        "source_type": "design_guide",
    },
    {
        "id": "visual_restaurant_rebellion_social_workflow",
        "title": "Restaurant Rebellion social media workflow",
        "url": "https://restaurantrebellion.com/social-media-workflow",
        "workflow": "小餐馆视觉营销物料制作与发布工作流",
        "proof_point": "餐饮社媒营销包含内容准备、caption、排期、发布和复盘等连续人工步骤。",
        "step_refs": ["内容准备", "文案撰写", "排期发布", "效果复盘"],
        "inefficiencies": ["沟通或审核成本", "人工重复"],
        "source_type": "workflow_guide",
    },
    {
        "id": "visual_sprout_social_restaurant_guide",
        "title": "Sprout Social guide to social media for restaurants and bars",
        "url": "https://sproutsocial.com/insights/bars-restaurants-social-media-guide/",
        "workflow": "小餐馆视觉营销物料制作与发布工作流",
        "proof_point": "餐厅需要持续发布图片、活动、菜单和品牌内容以影响用户决策。",
        "step_refs": ["图片内容发布", "活动推广", "品牌内容维护", "多平台运营"],
        "inefficiencies": ["信息搬运", "判断成本"],
        "source_type": "industry_guide",
    },
    {
        "id": "visual_menustudio_ai",
        "title": "MenuStudio AI",
        "url": "https://menustudio.ai/",
        "workflow": "小餐馆视觉营销物料制作与发布工作流",
        "proof_point": "已有产品验证了手机照片到餐厅菜单图、外卖图和广告图的商业需求。",
        "step_refs": ["手机拍照", "菜单图生成", "广告图生成"],
        "inefficiencies": ["人工重复", "判断成本"],
        "source_type": "competitor",
    },
    {
        "id": "visual_foodframe_authenticity",
        "title": "FoodFrame.ai",
        "url": "https://foodframe.ai/",
        "workflow": "小餐馆视觉营销物料制作与发布工作流",
        "proof_point": "餐饮图片 AI 工具强调基于真实菜品照片增强，说明真实性风控是关键要求。",
        "step_refs": ["真实菜品照片", "图片增强", "发布前确认"],
        "inefficiencies": ["审核或沟通成本"],
        "source_type": "competitor_risk",
    },
    {
        "id": "visual_plated_studio",
        "title": "Plated Studio",
        "url": "https://platedstudio.app/",
        "workflow": "小餐馆视觉营销物料制作与发布工作流",
        "proof_point": "餐厅照片、QR 菜单主页、社媒文案和广告活动可以整合成连续视觉运营工作流。",
        "step_refs": ["照片整理", "QR 菜单主页", "社媒文案", "广告活动"],
        "inefficiencies": ["信息搬运", "人工重复", "判断成本"],
        "source_type": "competitor",
    },
    {
        "id": "menu_update_help_center",
        "title": "Restaurant menu management help guide",
        "url": "https://support.toasttab.com/s/article/Menu-Management-Overview",
        "workflow": "外卖/堂食菜单图片与信息更新工作流",
        "proof_point": "菜单管理包含菜品、价格、分类、图片和可售状态等持续维护动作。",
        "step_refs": ["菜品新增", "价格维护", "图片更新", "可售状态检查"],
        "inefficiencies": ["信息搬运", "人工重复", "审核或沟通成本"],
        "source_type": "platform_help",
    },
    {
        "id": "complaint_zendesk_restaurant_service",
        "title": "Restaurant customer service guide",
        "url": "https://www.zendesk.com/blog/restaurant-customer-service/",
        "workflow": "餐厅客诉与退款处理工作流",
        "proof_point": "餐饮服务需要记录用户问题、判断责任、沟通补偿和复盘服务质量。",
        "step_refs": ["接收投诉", "记录问题", "判断责任", "沟通补偿", "复盘"],
        "inefficiencies": ["判断成本", "沟通或审核成本", "信息搬运"],
        "source_type": "industry_guide",
    },
    {
        "id": "inventory_procurement_restaurant365",
        "title": "Restaurant inventory management workflow",
        "url": "https://www.restaurant365.com/blog/restaurant-inventory-management/",
        "workflow": "餐厅库存盘点与采购补货工作流",
        "proof_point": "餐厅库存管理涉及盘点、消耗记录、采购、验收和成本控制等连续人工流程。",
        "step_refs": ["库存盘点", "消耗记录", "采购补货", "到货验收", "成本复盘"],
        "inefficiencies": ["人工重复", "信息搬运", "判断成本"],
        "source_type": "industry_guide",
    },
    {
        "id": "complaint_webstaurantstore_handling",
        "title": "How to Handle Customer Complaints In Your Restaurant",
        "url": "https://www.webstaurantstore.com/blog/3776/how-to-handle-customer-complaints.html",
        "workflow": "餐厅客诉与退款处理工作流",
        "proof_point": "公开指南描述了餐厅投诉处理需要识别投诉类型、由中立人员介入、给出道歉、补偿或免单等解决方案。",
        "step_refs": ["接收投诉", "识别投诉类型", "收集事实", "提出补偿方案", "复盘服务问题"],
        "inefficiencies": ["判断成本", "沟通或审核成本", "信息搬运"],
        "source_type": "industry_guide",
    },
    {
        "id": "complaint_refund_policy_template",
        "title": "Restaurant Refund Policy Template",
        "url": "https://www.restaurantsprofitsystems.com/assets/pdfs/Restaurant-Refund-Policy-Template.pdf",
        "workflow": "餐厅客诉与退款处理工作流",
        "proof_point": "退款政策模板证明餐厅需要把退款条件、顾客预期、例外情况和责任边界固化为可执行规则。",
        "step_refs": ["接收退款请求", "核对退款条件", "判断责任边界", "审批补偿", "记录处理结果"],
        "inefficiencies": ["判断成本", "沟通或审核成本"],
        "source_type": "policy_template",
    },
    {
        "id": "inventory_toast_purchase_receive",
        "title": "Toast Retail: Generate Purchase Orders & Receive Inventory",
        "url": "https://support.toasttab.com/article/Toast-Retail-Generate-Purchase-Orders-Receive-Inventory",
        "workflow": "餐厅库存盘点与采购补货工作流",
        "proof_point": "Toast 帮助文档展示了从采购单创建、发送、按采购单收货到发票收货的连续库存/采购流程。",
        "step_refs": ["查看采购与收货页", "创建采购单", "发送给供应商", "按采购单收货", "通过发票收货"],
        "inefficiencies": ["人工重复", "信息搬运", "审核或沟通成本"],
        "source_type": "platform_help",
    },
    {
        "id": "inventory_bluecart_procurement_workflow",
        "title": "Restaurant Inventory Management Software for Food and Beverage Businesses",
        "url": "https://www.bluecart.com/restaurant-inventory-management-software",
        "workflow": "餐厅库存盘点与采购补货工作流",
        "proof_point": "BlueCart 描述了库存计数、供应商连接、采购流、按采购单收货和差异标记，能证明采购补货是连续工作流。",
        "step_refs": ["库存计数", "连接供应商", "创建采购订单", "跟踪配送状态", "收货并标记差异"],
        "inefficiencies": ["人工重复", "信息搬运", "判断成本"],
        "source_type": "product_workflow",
    },
    {
        "id": "noise_ai_generated_food_risk",
        "title": "Public discussion about AI food photos misleading customers",
        "url": "https://www.reddit.com/r/antiai/comments/1thi59s/restaurants_are_now_using_ai_photos_for_menu/",
        "workflow": "纯 AI 生图娱乐",
        "proof_point": "AI 菜品图可能误导顾客，应作为风险证据而非候选工作流核心证据。",
        "step_refs": ["AI 生图", "发布争议"],
        "inefficiencies": ["审核或沟通成本"],
        "source_type": "risk_noise",
    },
]
